language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - travis_wait 30 cargo build --verbose --all
  - travis_wait 20 cargo test --verbose --all
