[profile.release]
#debug = true
strip = true  # Automatically strip symbols from the binary.

[workspace]
resolver = "2"

members = [
    "core/codegen",
    "core/dtn7",

    # internal
    "examples"
]