[package]
name = "dtn7"
version = "0.1.0"
authors = ["Lars Baumgaertner <baumgaertner@cs.tu-darmstadt.de>"]
edition = "2018"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.85"
serde_cbor = "0.9"
serde_json = "1.0"
#serde_tuple = "0.2.2"
serde_bytes = "0.10.5"
url = "1.7"
crc = "^1.0.0"
byteorder = "1"
derive_builder = "0.7.1"


[lib]
name = "dtn7"
path = "src/lib.rs"

[[bin]]
name = "dtnd"
path = "src/main.rs"
