[package]
name = "dtn7"
version = "0.4.2"
authors = ["Lars Baumgaertner <baumgaertner@cs.tu-darmstadt.de>"]
description = "Rust delay-tolerant-networking daemon and CLI tools based upon bp7 (dtn version 7 draft)"
edition = "2018"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities", "network-programming"]
repository    = "https://github.com/gh0st42/dtn7-rs"
keywords = ["peer2peer", "dtn"]
exclude = [".vscode/", ".travis.yml"]
readme = "README.md"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.85"
serde_cbor = "0.10"
serde_json = "1.0"
serde_bytes = "0.11"
url = "2.0"
crc = "^1.0.0"
byteorder = "1"
derive_builder = "0.7.1"
rand = "0.7"
tokio = "0.1.18"
futures = "0.1"
hyper = "0.12.25"
pretty_env_logger = "0.3"
log = "0.4"
net2 = "0.2"
bytes = "0.4"
clap = "2.32.0"
config = "0.9"
lazy_static = "1.3.0"
bp7 = "0.3"
reqwest = "0.9"
crossbeam = "0.7"

[lib]
name = "dtn7"
path = "src/lib.rs"

